PLAYER_NAME = "heinrich"

CONSOLE_TOGGLE_KEY = "f1"
CONSOLE_AUTOCOMPLETE_KEY = "tab"
CONSOLE_AUTOHELP_KEY = "f1"
CONSOLE_SCROLL_UP_KEY = "page_up"
CONSOLE_SCROLL_DOWN_KEY = "page_down"
CONSOLE_PREVIOUS_COMMAND_KEY = "arrow_up"
CONSOLE_NEXT_COMMAND_KEY = "arrow_down"

MOVE_FORWARD_KEY = "w"
MOVE_BACKWARD_KEY = "s"
MOVE_LEFT_KEY = "a"
MOVE_RIGHT_KEY = "d"
MOVE_JUMP_KEY = "space"
MOVE_CROUCH_KEY = "control"
MOVE_SPRINT_KEY = "shift"

PRIMARY_FIRE_KEY = "mouse1"
SECONDARY_FIRE_KEY = "mouse2"
AIM_FIRE_KEY = "mouse3"

MOUSE_X_SPEED = 8.0
MOUSE_Y_SPEED = 1.2

USE_KEY = "e"
FLASHLIGHT_KEY = "f"
DROP_ITEM_KEY = ""
THROW_GRENADE_KEY = "g"

ITEMS_SLOT_1_KEY = "1"
ITEMS_SLOT_2_KEY = "2"
ITEMS_SLOT_3_KEY = "3"
ITEMS_SLOT_4_KEY = "4"
ITEMS_SLOT_5_KEY = "5"
ITEMS_SLOT_6_KEY = "6"
ITEMS_SLOT_7_KEY = "7"
ITEMS_SLOT_8_KEY = "8"
ITEMS_SLOT_9_KEY = "9"
ITEMS_SLOT_0_KEY = "0"

